コンフリクトを打ち消しました
KimuraYu45z/datascience-book pull request #26
Opened 2021-08-20 00:42 UTC by Shibuzou

解消できてますでしょうか？

2021-08-20 00:48 UTC, KimuraYu45z requested changes

2021-08-20 00:48 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
これ数学的に間違ってる気がします。確率変数の取る値が自然数であることを暗黙的に仮定しないとこうならない。

離散であることと非自然数とることは背反でないです。

2021-08-20 00:48 UTC, KimuraYu45z commented on main.tex
> + p(X=k)={}_nC_k p^ k(1-p)^{n-k}
小文字pはカッコの中に事象ではなく実数を入れるのでX=kは入れないです、これは事象です。

2021-08-20 00:48 UTC, KimuraYu45z commented on main.tex
> +参考: https://bellcurve.jp/statistics/course/6986.html
本文にリンク入れるの微妙だと思うんで、今後これは参考文献リストに引っ越すものとしてとりあえず置いときましょう。

2021-08-20 00:48 UTC, KimuraYu45z commented on main.tex
> +$
自由度はνで書いてほしいです。\nu

2021-08-20 01:23 UTC, Shibuzou commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
すみません、ここのレビュー詳しくお願いします

2021-08-20 01:24 UTC, Shibuzou commented on main.tex
> + p(X=k)={}_nC_k p^ k(1-p)^{n-k}
p(k)={}_nC_k q^ k(1-q)^{n-k}
ということでしょうか？

2021-08-20 01:24 UTC, Shibuzou commented on main.tex
> +参考: https://bellcurve.jp/statistics/course/6986.html
これはメモのためなので書いたら消します.

2021-08-20 01:24 UTC, Shibuzou commented on main.tex
> +$
失礼しました. 
\nuで書き換えます.

2021-08-20 01:28 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
たとえばそれぞれ二分の一の確率で0.7の値と1.3の値をとる離散確率変数とかですね。

2021-08-20 01:29 UTC, KimuraYu45z commented on main.tex
> + p(X=k)={}_nC_k p^ k(1-p)^{n-k}
そうですね。
kじゃなくxで統一してもいいとは思います。

2021-08-20 01:34 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
ようするに総和記号あたりが怪しいです。

2021-08-20 01:44 UTC, Shibuzou commented on main.tex
> + p(X=k)={}_nC_k p^ k(1-p)^{n-k}
p(x)={}_nC_x q^ x(1-q)^{n-x}
とします

2021-08-20 02:03 UTC, Shibuzou commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
その場合,２項分布になるので確率質量関数は p(k)={}_nC_k q^ k(1-q)^{n-k}になるということは
p(x)=P(X=x)ということですか?

2021-08-20 02:05 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
はい、離散確率変数に関してはそれが成り立ちます。
連続確率変数はそうはならないですが。

2021-08-20 02:07 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
二項分布うんぬんあたりは関係ない話だと思います。

2021-08-20 02:11 UTC, Shibuzou commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
すみません, 
では
離散確率確率変数に対しては, 確率質量変数はp(x)=P(X=x)と与えられる.
という書き方であってますか?

2021-08-20 02:13 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
はい、それはあってます。でも大文字Pが関わる話なので8章に書いたほうがいいですね。

2021-08-20 02:17 UTC, Shibuzou commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
そうですよね〜
ここでは「確率質量関数は離散型確率変数に対して確率分布を与える関数です. 」
という日本語にしとけばいいですか？

2021-08-20 02:19 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
そうですね。表現に悩む箇所は9月に加筆修正していけばいいのでいまは悩まずに済むとこバーっと書いていきましょう。ペースわりと目標に比べてヤバいと思いますし。

2021-08-20 02:21 UTC, Shibuzou commented on main.tex
> + p(a \leq x \leq b) = \sum_{i=a}^b p(x_i)
了解です. 
ペース遅いのまずいですよね〜
上げていきます!

2021-08-20 02:37 UTC, KimuraYu45z approved these changes

2021-08-20 02:38 UTC, merged

2021-08-21 01:54 UTC, KimuraYu45z commented on main.tex
> + p(a \leq x \leq b) = \int_a^b f(x)dx
レビュー漏れでした。これ間違ってるので修正しておきます（小文字pは事象を中に入れない

2021-08-21 01:54 UTC, KimuraYu45z commented on main.tex
> + p(x)\geq 0, \quad\ \int_{-{\infty}}^{\infty} f(x)dx = 1
これも違いました